### ISSUE TITLE
Kernel panics during install

### ISSUE THREAD

**Issue by thinkingsand** [kinoute/Hack-HP-EliteBook-850-G5#3]
I'm trying to install the latest Mojave version on a HP EliteBook 850 G5 with a slightly different config to yours (i5-8250U, 8GB DDR4, 256GB SSD) and it keeps kernel panicking about 2/3 through the setup. In the log it happens just after "Verifying: InstallESD.dmg". Attempting to boot from the second stage of the install on the SSD results in it starting for a few minutes before panicking. I'm using the second to latest bios from October 2019. Trying to boot the installer on the latest bios results in it getting stuck on the line of pluses after "End RandomSeed". I've tried redownloading the install app twice and tried multiple USBs. My bios is configured identically to your screenshots. Do you have a fix for this?

**Comment by thinkingsand** [comment]
*Forgot to add that my trackpad doesn't work either but that can wait until after the install.

**Comment by thinkingsand** [comment]
This has got me confused. I've had a further look at the error messgaes and the first crash in the installer isn't a kernel panic at all. It's just a standard shutdown, it cleanly unmounts drives and there's no memory dump information. On the second crash when booting from the SSD, there's no visible text, just a fade to a black screen from the apple logo before restarting. I do however, get the "Your computer restarted because of a problem" warning on the next boot so it's obviously kernel panicking just somehow with no debug info. I've also tried with @kecinzer's OpenCore config and get the same results.

**Comment by kinoute** [comment]
Did you run the install with the `-v` flag to check if there was an error detailed?

It looks like either a BIOS error (bios too recent) or a installer error. I had difficulties installing macOS on this machine with a USB3 Key. Had to use a USB2 key or IIRC, a USB3 key plugged to USB2 hub. Otherwise, the installer will fail at some point.

**Comment by thinkingsand** [comment]
Hi, thanks for responding. Yes, I've been running the installer in verbose mode. What bios exactly have you managed to get this running on (I'm using Q78 Ver 1.09.01 10/16/2019)? So far I've tried 3 usb keys (two USB2 one USB3) and all fail at exactly the same point. Putting the USB3 into a USB2 hub gets the exact same result. Does definitely seem like a bios error, when considering the trackpad doesn't work and I've had it not boot up at all on the first two bios revisions and the most recent.

**Comment by kinoute** [comment]
I use Q78 Ver. 01.08.01 07/18/2019

**Comment by kinoute** [comment]
Some people had problems after updating from my version to yours:

https://h30434.www3.hp.com/t5/Notebook-Operating-System-and-Recovery/Issues-after-update-the-last-BIOS-HP-EliteBook-850-G5-HP/td-p/7302720

**Comment by thinkingsand** [comment]
All fixed. Turns out part way through the 850 G5s production HP switched to Samsung PM981 SSDs which have issues with macOS. Installing NVMEFix.kext (need to compile from source, the release is too old) fixes all the kernel panics. I'll write up a PR for the readme with extra info. Thanks for helping.

**Comment by kinoute** [comment]
Nice. I would love to hear if you get problems after sleep/waking up. I heard SSD/NVME could be the reason of our problems. Might try this kext.
